<?php

return [
    'company' => 'Professional Papers S.A.S. (PROPAPS S.A.S.)',
    'concept' => 'Inteligencia Humana + Inteligencia Artificial = Inteligencia Hibrida',
    'focus' => 'Ciencias Sociales y Educacion',
    'plans' => [
        [
            'id' => 'asesoria-esencial',
            'db_name' => 'Paquete Asesoría Esencial',
            'name' => 'Paquete Asesoria Face to Face',
            'tag' => 'Ideal para iniciar',
            'badge' => '25% OFF',
            'featured' => false,
            'headline_price' => 'Desde 225 USD + IVA',
            'short_description' => 'La mejor solucion y con los mejores precios del mercado para ordenar ideas, recibir feedback experto de primer nivel y avanzar con confianza en el momento clave de su proyecto.',
            'benefits' => [
                'Sesion sincronica acordada por las partes.',
                'Comentarios en documento eventualmente entregado por el cliente (hasta 80 paginas).',
                'Transcripcion de la grabacion con comentarios.',
                'Identificacion y desarrollo de ideas fuerza.',
                'Mapa conceptual y plan de accion en linea Premium.',
            ],
            'lines' => [
                [
                    'name' => 'Linea Estandar',
                    'intro' => 'La solucion mas inteligente y accesible para quienes necesitan ordenar ideas, recibir feedback experto y avanzar rapidamente y con confianza. Incluye una sesion sincronica acordada que usted elige en el momento clave de su propio proceso.',
                    'includes' => [
                        'Una sesion sincronica acordada por las partes.',
                        'Comentarios en documento eventualmente entregado por el cliente (hasta 80 paginas).',
                        'Transcripcion de la grabacion con comentarios.',
                        'Identificacion y desarrollo de ideas fuerza.',
                    ],
                    'advantage' => 'Resultados de alto impacto inmediato con la mejor relacion calidad-precio del mercado. Perfecto para formulacion, desarrollo o cierre de proyecto con resultados de alto impacto a partir de una sola sesion.',
                    'costs' => ['225 USD (precio con descuento especial -25% off-)'],
                    'note' => 'Si el servicio requerido es de correccion, redaccion, acompanamiento o proceso de publicacion, debe contratar el servicio correspondiente.',
                ],
                [
                    'name' => 'Linea Premium',
                    'intro' => 'El acompanamiento estrategico de elite que le permite decidir libremente el numero, el momento y la frecuencia de las sesiones sincronicas, asi como proponer los plazos segun sus necesidades reales.',
                    'includes' => [
                        'Hasta 5 sesiones sincronicas programadas y a la medida de las necesidades del cliente.',
                        'Comentarios en documento eventualmente entregado por el cliente (hasta 80 paginas).',
                        'Mapa conceptual.',
                        'Transcripcion de la grabacion con comentarios.',
                        'Identificacion y desarrollo de ideas fuerza.',
                        'Plan de accion.',
                    ],
                    'advantage' => 'Flexibilidad total + feedback continuo de primer nivel para proyectos complejos o deadlines exigentes.',
                    'costs' => ['850 USD (precio con descuento especial -25% off-)'],
                    'note' => 'Si el servicio requerido es de correccion, redaccion o proceso de publicacion, debe contratar el servicio correspondiente.',
                ],
            ],
        ],
        [
            'id' => 'correccion-completa',
            'db_name' => 'Paquete Corrección Completa',
            'name' => 'Paquete Correccion Completa',
            'tag' => 'Mas demandado',
            'badge' => 'Inteligencia Hibrida',
            'featured' => false,
            'headline_price' => 'Desde 650 USD + IVA',
            'short_description' => 'Calidad profesional con la mejor relacion calidad/precio del mercado. Permite resultados impecables mediante feedback experto e Inteligencia Hibrida.',
            'benefits' => [
                'Correccion completa: ortografia, estilo, argumentacion y coherencia.',
                'Formato APA 7 o el exigido por la Unidad Academica.',
                'Comentarios detallados en el documento.',
                'Plazos Estandar, Express o Turbo.',
                'Sesiones sincronicas segun la linea elegida.',
            ],
            'lines' => [
                [
                    'name' => 'Linea Estandar',
                    'intro' => 'Pulimos y perfeccionamos su manuscrito hasta alcanzar los estandares academicos mas exigentes, con una sesion sincronica acordada por ambas partes.',
                    'deadlines' => ['Estandar: hasta 15 dias calendario maximo', 'Express: entre 14 y 10 dias calendario', 'Turbo: menos de 10 dias calendario'],
                    'includes' => [
                        'Una sesion sincronica acordada por ambas partes.',
                        'Correccion completa: ortografia, estilo, argumentacion, coherencia y formato APA 7 o el exigido por su Unidad Academica.',
                        'Comentarios detallados en el documento.',
                    ],
                    'advantage' => 'Resultado profesional y limpio a un precio altamente competitivo, ideal para manuscritos ya avanzados.',
                    'costs' => [
                        '650 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 100 USD.',
                        'Modo Express: 750 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 175 USD.',
                        'Modo Turbo: 950 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 175 USD.',
                    ],
                    'note' => 'Si el servicio requerido es de desarrollo de ideas fuerza, redaccion, proceso de publicacion o acompanamiento, debe contratar el servicio correspondiente.',
                ],
                [
                    'name' => 'Linea Premium',
                    'intro' => 'La correccion integral de alto nivel. Sesiones sincronicas a su medida (hasta 5 sesiones) y feedback asincronico de hasta 3 entregas parciales de revision.',
                    'deadlines' => ['Estandar: hasta 12 dias calendario maximo', 'Express: entre 11 y 8 dias calendario', 'Turbo: menos de 7 dias calendario'],
                    'includes' => [
                        'Hasta 5 sesiones de trabajo sincronico a la medida del cliente.',
                        'Correccion completa y formato APA 7 o el exigido por su universidad.',
                        'Comentarios detallados.',
                        'Ajustes progresivos hasta lograr la version optima dentro de los plazos acordados.',
                    ],
                    'advantage' => 'Maximo rigor academico y respaldo total para publicaciones indexadas o de alta exigencia.',
                    'costs' => [
                        '850 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 100 USD.',
                        'Modo Express: 950 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 175 USD.',
                        'Modo Turbo: 1250 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 175 USD.',
                    ],
                    'note' => 'Si el servicio requerido es de desarrollo de ideas fuerza, redaccion, proceso de publicacion o acompanamiento, debe contratar el servicio correspondiente.',
                ],
            ],
        ],
        [
            'id' => 'redaccion-express-profesional',
            'db_name' => 'Paquete Redacción Express Profesional',
            'name' => 'Paquete Redaccion Profesional',
            'tag' => 'Desde cero',
            'badge' => 'Alto nivel',
            'featured' => false,
            'headline_price' => 'Desde 0,14 USD por palabra',
            'short_description' => 'Redaccion experta desde cero o reescritura integral a partir de contenido, notas, datos o ideas iniciales.',
            'benefits' => [
                'Redaccion completa con Inteligencia Hibrida.',
                'Estructura academica segun normas exigidas.',
                'Correccion completa.',
                'Sesiones sincronicas segun la linea elegida.',
                'Trabajo sobre documentos minimo 4.000 palabras.',
            ],
            'lines' => [
                [
                    'name' => 'Linea Estandar',
                    'intro' => 'Redaccion completa y profesional desde cero y sobre insumos, con una sesion sincronica que usted planea y programa.',
                    'includes' => [
                        'Una sesion sincronica programada por el equipo de propaps.com.',
                        'Estructura del documento segun normas exigidas por la dependencia.',
                        'Correccion completa.',
                        'Redaccion express con entregas mayores a 5 dias y menores de 15 dias calendario.',
                        'Aplicacion de Inteligencia Hibrida con criterio humano atento a los requerimientos del cliente.',
                    ],
                    'advantage' => 'Solucion rapida y confiable para deadlines ajustados. Resultados profesionales a un precio competitivo.',
                    'costs' => ['Pregrado: 0,14 USD x palabra.', 'Maestria: 0,17 USD x palabra.', 'Doctorado: 0,23 USD x palabra.'],
                    'note' => 'Si el servicio requerido es de coaching, publicacion o acompanamiento, debe contratar el servicio correspondiente.',
                ],
                [
                    'name' => 'Linea Premium',
                    'intro' => 'Redaccion express de maximo nivel donde usted decide el numero y momento de las sesiones sincronicas y propone los plazos de entrega.',
                    'includes' => [
                        'Proceso de acompanamiento en la redaccion.',
                        'Revision de coherencia y aporte de originalidad identificando y desarrollando ideas fuerza.',
                        'Hasta 5 sesiones sincronicas programadas por el cliente.',
                        'Estructura del documento segun normas exigidas por la dependencia.',
                        'Correccion completa.',
                        'Redaccion express con plazos acordados con propaps.com.',
                        'Revision express por pares (doble ciego) cuando aplique.',
                        'Analisis y desarrollo de ideas fuerza para definir el aporte de nuevo conocimiento.',
                    ],
                    'advantage' => 'Entrega ultra-personalizada y de elite para quienes buscan el mas alto estandar en tiempos cortos.',
                    'costs' => ['Pregrado: 0,17 USD x palabra.', 'Maestria: 0,23 USD x palabra.', 'Doctorado: 0,27 USD x palabra.'],
                    'note' => 'Si el servicio requerido es de coaching, publicacion o acompanamiento, debe contratar el servicio correspondiente.',
                ],
            ],
        ],
        [
            'id' => 'segundo-tutor',
            'db_name' => 'Paquete Segundo Tutor',
            'name' => 'Paquete Segundo Tutor',
            'tag' => 'Acompanamiento continuo',
            'badge' => 'Trimestral',
            'featured' => false,
            'headline_price' => 'Desde 900 USD/mes + IVA',
            'short_description' => 'Apoyo academico mensual estructurado para tesis, monografias y trabajos de grado con productos tangibles.',
            'benefits' => [
                'Sesiones sincronicas mensuales.',
                'Correccion completa de cada capitulo.',
                'Apoyo en desarrollo de ideas fuerza.',
                'Alineacion con tutor, asesor y Unidad Academica.',
                'Productos completos cada mes en linea Premium.',
            ],
            'lines' => [
                [
                    'name' => 'Linea Estandar',
                    'intro' => 'El apoyo academico mensual mas eficiente. Ideal para la produccion tripartita, compleja y de alta calidad de tesis, monografias y trabajos de grado.',
                    'includes' => [
                        'Una sesion sincronica al final de cada mes por 3 meses.',
                        'Correccion completa de cada capitulo.',
                        'Apoyo en desarrollo de ideas fuerza.',
                        'Apoyo en los requerimientos del tutor o asesor del tesista y Unidad Academica.',
                    ],
                    'advantage' => 'Ideal para mantener el ritmo sin sobrecostos. Acompanamiento constante y estructurado a precio accesible durante todo el trimestre.',
                    'costs' => ['Pregrado: 900 USD mes.', 'Maestria: 1100 USD mes.', 'Doctorado: 1500 USD mes.'],
                    'note' => 'Si el servicio requerido es de coaching, redaccion, publicacion o correccion aislada, debe contratar el servicio correspondiente.',
                ],
                [
                    'name' => 'Linea Premium',
                    'intro' => 'El tutor de elite que se adapta completamente a usted.',
                    'includes' => [
                        'Hasta 5 sesiones sincronicas mensuales programadas y planeadas por el cliente.',
                        'Correccion completa de cada capitulo.',
                        'Apoyo en desarrollo de ideas fuerza.',
                        'Apoyo en los requerimientos del tutor o asesor del tesista.',
                        'Plazos de entrega a la medida del cliente.',
                        'Productos completos cada mes segun las necesidades del cliente.',
                    ],
                    'advantage' => 'Experiencia personalizada de alto rendimiento que acelera la graduacion y optimiza la calidad del trabajo final.',
                    'costs' => ['Pregrado: 1200 USD mes.', 'Maestria: 1500 USD mes.', 'Doctorado: 1850 USD mes.'],
                    'note' => 'Si el servicio requerido es de coaching, redaccion, publicacion o correccion aislada, debe contratar el servicio correspondiente.',
                ],
            ],
        ],
        [
            'id' => 'premium-publicacion-cientifica',
            'db_name' => 'Paquete Premium Publicación Científica',
            'name' => 'Paquete Modo Indexacion para Publicaciones Cientificas',
            'tag' => 'Mas completo',
            'badge' => 'Recomendado',
            'featured' => true,
            'headline_price' => 'Desde 950 USD + IVA',
            'short_description' => 'Para investigadores que buscan convertir su manuscrito en un articulo publicable e indexado en bases de prestigio.',
            'benefits' => [
                'Correccion completa.',
                'Seleccion estrategica de revista target.',
                'Adaptacion a revista.',
                'Revision simulada por pares.',
                'Acompanamiento hasta publicacion.',
            ],
            'lines' => [
                [
                    'name' => 'Linea Estandar',
                    'intro' => 'El camino mas directo y economico hacia la publicacion.',
                    'includes' => [
                        'Una sesion sincronica.',
                        'Correccion completa.',
                        'Adaptacion a revista a partir de seleccion estrategica.',
                        'Revision simulada por pares.',
                        'Acompanamiento hasta la publicacion.',
                    ],
                    'advantage' => 'Resultados publicables en tiempo express, a precio accesible sin complicaciones.',
                    'costs' => [
                        'Pregrado: 950 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 150 USD.',
                        'Maestria: 1200 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 200 USD.',
                        'Doctorado: 1600 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 200 USD.',
                    ],
                    'note' => 'Si el servicio requerido es de coaching, redaccion, correccion o acompanamiento, debe contratar el servicio correspondiente.',
                ],
                [
                    'name' => 'Linea Premium',
                    'intro' => 'El acompanamiento completo desde el manuscrito hasta la publicacion real. Para quienes la perfeccion importa.',
                    'includes' => [
                        'Libre eleccion del numero, momento y frecuencia de las sesiones sincronicas (hasta 5 sesiones).',
                        'Identificacion, analisis y desarrollo de ideas fuerza y aportes de nuevo conocimiento.',
                        'Correccion completa.',
                        'Seleccion estrategica de revista y adecuacion del manuscrito.',
                        'Revision simulada por pares.',
                        'Analisis de observaciones y ajustes post-revision.',
                        'Garantia real de 1 ano de acompanamiento.',
                    ],
                    'advantage' => 'Exito garantizado en el proceso editorial con el maximo nivel de personalizacion y respaldo.',
                    'costs' => [
                        'Pregrado: 1300 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 150 USD.',
                        'Maestria: 1500 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 200 USD.',
                        'Doctorado: 1850 USD x documento = o < 8.000 palabras. Cada 1000 palabras adicionales: + 200 USD.',
                    ],
                    'note' => 'Si el servicio requerido es de coaching, redaccion, correccion o acompanamiento, debe contratar el servicio correspondiente.',
                ],
            ],
        ],
    ],
];
