<?php

return [
    'company' => 'Professional Papers S.A.S. (PROPAPS S.A.S.)',
    'concept' => 'Inteligencia Humana + Inteligencia Artificial = Inteligencia Híbrida',
    'focus' => 'Ciencias Sociales y Educación',
    'terms' => [
        'Todos los servicios se pagan en su totalidad al momento de la contratación.',
        'Los valores se presentan en USD. El IVA aplicable es del 19%.',
        'Professional Papers S.A.S. (PROPAPS S.A.S.) emite facturación electrónica y cumple la normativa fiscal colombiana.',
    ],
    'plans' => [
        [
            'id' => 'asesoria-esencial',
            'db_name' => 'Paquete Asesoría Esencial',
            'name' => 'Paquete Asesoría Esencial',
            'tag' => 'Mejor para iniciar',
            'discount' => '45% OFF',
            'base_price' => '82',
            'discounted_price' => '45',
            'final_price' => '53,55',
            'headline_price' => '53,55',
            'headline_prefix' => '',
            'headline_suffix' => 'final con IVA',
            'featured' => false,
            'short_description' => 'Sesión experta para ordenar ideas y convertir dudas iniciales en próximos pasos accionables.',
            'description' => 'Servicio de entrada ideal para ordenar ideas y recibir feedback experto de alto nivel en una sola sesión. La Inteligencia Híbrida permite entregar resultados accionables inmediatos a precio competitivo.',
            'benefits' => [
                '1 sesión en vivo de 1 hora',
                'Ordenamiento de ideas',
                'Feedback estratégico',
                'Mapa conceptual o esquema visual',
                'Resumen de fortalezas y riesgos',
            ],
            'pricing_rows' => [],
            'detail_rows' => [
                [
                    'stage' => 'Sesión 1',
                    'timing' => '1 hora en vivo',
                    'activities' => 'Ordenar ideas, identificar aportes novedosos, feedback estratégico, recepción de documentación y orientación inicial según necesidades.',
                    'deliverables' => 'Grabación completa, resumen ejecutivo de fortalezas y riesgos, mapa conceptual o esquema visual y recomendaciones concretas.',
                ],
            ],
        ],
        [
            'id' => 'correccion-completa',
            'db_name' => 'Paquete Corrección Completa',
            'name' => 'Paquete Corrección Completa',
            'tag' => 'Corrección académica profunda',
            'discount' => '10% OFF',
            'base_price' => '222',
            'discounted_price' => '200',
            'final_price' => '238',
            'headline_price' => '238',
            'headline_prefix' => 'Desde',
            'headline_suffix' => 'final con IVA',
            'featured' => false,
            'short_description' => 'Corrección profunda de manuscritos académicos con comentarios y recomendaciones de publicación.',
            'description' => 'Servicio especializado en pulir y corregir manuscritos para alcanzar estándares académicos en Ciencias Sociales y Educación.',
            'benefits' => [
                'Opciones hasta 40, 60 o 120 páginas',
                '2 sesiones de trabajo',
                'Análisis profundo con Inteligencia Híbrida',
                'Manuscrito limpio',
                'Comentarios detallados',
                'Recomendaciones de publicación',
            ],
            'pricing_rows' => [
                ['label' => 'Hasta 40 páginas / 12.000 palabras', 'base' => '222', 'discounted' => '200', 'final' => '238'],
                ['label' => 'Hasta 60 páginas / 18.000 palabras', 'base' => '311', 'discounted' => '280', 'final' => '333,20'],
                ['label' => 'Hasta 120 páginas / 36.000 palabras', 'base' => '533', 'discounted' => '480', 'final' => '571,20'],
            ],
            'detail_rows' => [
                [
                    'stage' => 'Sesión 1',
                    'timing' => '1 hora',
                    'activities' => 'Presentación del caso y recepción del manuscrito.',
                    'deliverables' => 'Grabación y compromiso formal.',
                ],
                [
                    'stage' => 'Sesión 2',
                    'timing' => 'Máximo 15 días hábiles',
                    'activities' => 'Análisis profundo con Inteligencia Híbrida.',
                    'deliverables' => 'Manuscrito limpio con comentarios detallados y recomendaciones de publicación.',
                ],
            ],
        ],
        [
            'id' => 'premium-publicacion-cientifica',
            'db_name' => 'Paquete Premium Publicación Científica',
            'name' => 'Paquete Premium Publicación Científica',
            'tag' => 'Recomendado para publicación',
            'discount' => '10% OFF',
            'base_price' => '1.000',
            'discounted_price' => '900',
            'final_price' => '1.071',
            'headline_price' => '1.071',
            'headline_prefix' => '',
            'headline_suffix' => 'final con IVA',
            'featured' => true,
            'short_description' => 'Acompañamiento integral desde el manuscrito hasta la publicación, con soporte por un año.',
            'description' => 'Servicio integral que acompaña al cliente desde la recepción del manuscrito hasta la publicación científica, con garantía real de apoyo durante un año.',
            'benefits' => [
                '5 sesiones o etapas de acompañamiento',
                'Texto corregido y optimizado',
                'Selección estratégica de revista',
                'Revisión simulada por pares',
                'Soporte documental para envío',
                'Acompañamiento por 1 año',
            ],
            'pricing_rows' => [],
            'detail_rows' => [
                [
                    'stage' => 'Sesión 1',
                    'timing' => 'Día de contratación',
                    'activities' => 'Escucha activa, recepción de documentación e insumos, análisis inicial con Inteligencia Híbrida y registro de insumos aportados.',
                    'deliverables' => 'Informe detallado de observaciones y compromiso de texto listo para revisión por pares en la siguiente sesión.',
                ],
                [
                    'stage' => 'Sesión 2',
                    'timing' => '2 semanas después',
                    'activities' => 'Reunión en vivo, discusión de observaciones, acuerdos y selección estratégica de revista.',
                    'deliverables' => 'Texto corregido y optimizado; luego se envía a revisión simulada por pares.',
                ],
                [
                    'stage' => 'Sesión 3',
                    'timing' => '2 semanas después',
                    'activities' => 'Reunión en vivo para analizar comentarios y resultado de la revisión simulada por pares.',
                    'deliverables' => 'Plan de acción post-revisión.',
                ],
                [
                    'stage' => 'Sesión 4',
                    'timing' => 'Envío a revista',
                    'activities' => 'Sin trabajo sincrónico. El cliente envía el documento a la revista.',
                    'deliverables' => 'Soporte documental completo y artículo o documento en óptimas condiciones para envío.',
                ],
                [
                    'stage' => 'Sesión 5',
                    'timing' => 'Garantía si no se publica',
                    'activities' => 'Acompañamiento por 1 año y ajustes necesarios.',
                    'deliverables' => 'Nuevo manuscrito ajustado para otra revista.',
                ],
            ],
        ],
        [
            'id' => 'segundo-tutor',
            'db_name' => 'Paquete Segundo Tutor',
            'name' => 'Paquete Segundo Tutor',
            'tag' => 'Membresía trimestral',
            'discount' => '10% OFF',
            'renewal' => 'Renovación con 15% OFF adicional',
            'base_price' => '926',
            'discounted_price' => '833',
            'final_price' => '991',
            'headline_price' => '991',
            'headline_prefix' => 'Desde',
            'headline_suffix' => 'trimestre final con IVA',
            'featured' => false,
            'short_description' => 'Acompañamiento continuo como segundo tutor de élite durante todo el trimestre.',
            'description' => 'Acompañamiento continuo y estructurado como un segundo tutor de élite durante todo el trimestre para pregrado, posgrado y doctorado en Ciencias Sociales y Educación.',
            'benefits' => [
                '100% virtual con plataforma propia',
                '4 sesiones sincrónicas de 60 minutos',
                'Feedback asincrónico permanente',
                'Máximo 40 páginas por entrega',
                'Reportes mensuales y final trimestral',
                'Renovación con descuento adicional',
            ],
            'pricing_rows' => [
                ['label' => 'Pregrado', 'base' => '926', 'discounted' => '833', 'final' => '991', 'monthly' => '330', 'renewal' => '842'],
                ['label' => 'Posgrado', 'base' => '1.190', 'discounted' => '1.071', 'final' => '1.275', 'monthly' => '425', 'renewal' => '1.084'],
                ['label' => 'Doctorado', 'base' => '1.593', 'discounted' => '1.434', 'final' => '1.707', 'monthly' => '569', 'renewal' => '1.450'],
            ],
            'detail_rows' => [
                [
                    'stage' => 'Mes 1',
                    'timing' => 'Día 1',
                    'activities' => 'Sesión sincrónica y feedback asincrónico permanente.',
                    'deliverables' => 'Marco teórico y propuesta metodológica completa.',
                ],
                [
                    'stage' => 'Mes 2',
                    'timing' => 'Día 30',
                    'activities' => 'Sesión sincrónica, revisión de avances y reporte mensual.',
                    'deliverables' => 'Instrumentos más matriz de análisis o equivalente según el área y la Facultad.',
                ],
                [
                    'stage' => 'Mes 3',
                    'timing' => 'Días 60 y 90',
                    'activities' => 'Sesiones sincrónicas, revisión de entregas y cierre de trimestre.',
                    'deliverables' => 'Resultados/discusión o diapositivas más guion de defensa.',
                ],
                [
                    'stage' => 'Cierre',
                    'timing' => 'Fin del trimestre',
                    'activities' => 'Revisión integral hasta 120 páginas.',
                    'deliverables' => 'Producto final pulido, informe ejecutivo y plan de renovación.',
                ],
            ],
        ],
        [
            'id' => 'redaccion-express-profesional',
            'db_name' => 'Paquete Redacción Express Profesional',
            'name' => 'Paquete Redacción Express Profesional',
            'tag' => 'Entrega rápida',
            'discount' => '10% OFF',
            'base_price' => '222',
            'discounted_price' => '200',
            'final_price' => '238',
            'headline_price' => '238',
            'headline_prefix' => 'Desde',
            'headline_suffix' => 'final con IVA',
            'featured' => false,
            'short_description' => 'Redacción rápida para clientes con material completo y fechas límite ajustadas.',
            'description' => 'Servicio rápido y eficiente para clientes que entregan material completo y de buena calidad. Ideal para fechas límite ajustadas.',
            'benefits' => [
                'Opciones de 12.000 o 30.000 palabras',
                '2 sesiones de trabajo',
                'Análisis y redacción con Inteligencia Híbrida',
                'Manuscrito redactado',
                'Comentarios y recomendaciones',
                'Grabación y compromisos formales',
            ],
            'pricing_rows' => [
                ['label' => 'Documento base / 12.000 palabras / 40 páginas a 1,5', 'base' => '222', 'discounted' => '200', 'final' => '238'],
                ['label' => 'Monografía extendida / 30.000 palabras / 100 páginas a 1,5', 'base' => '556', 'discounted' => '500', 'final' => '595'],
            ],
            'detail_rows' => [
                [
                    'stage' => 'Sesión 1',
                    'timing' => '1 hora',
                    'activities' => 'Presentación del caso y entrega de material.',
                    'deliverables' => 'Grabación y compromisos formales.',
                ],
                [
                    'stage' => 'Sesión 2',
                    'timing' => 'Máximo 15 días hábiles',
                    'activities' => 'Análisis y redacción con Inteligencia Híbrida.',
                    'deliverables' => 'Manuscrito limpio con comentarios y recomendaciones.',
                ],
            ],
        ],
    ],
];
